#!/usr/bin/env bash
# write a Bash script that displays the content of the file /etc/passwd.
# your script should only display: username ,user id ,Home directory path for the user

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
